default_language_version:
  python: python3.10
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args:
          - '--unsafe'
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: 'https://github.com/psf/black'
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--line-length=88"]
  - repo: 'https://github.com/executablebooks/mdformat'
    rev: 0.7.16
    hooks:
      - id: mdformat
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
